### ISSUE TITLE
morphToMany relationship support

### ISSUE THREAD

**Issue by ariews** [october-widgets/tagbox#1]
First, thanks for this excellent widget, very useful and easy-to-use.

How I can get owl-tagbox work with morphToMany relationship?

Thanks.

**Comment by scottbedard** [comment]
This doesn't use polymorphism, but the Blog Tags plugin demonstrates how to use a relationship to manage your tags. Adjusting it to work with a polymorphic relationship should be pretty straight forward
https://github.com/scottbedard/blogtags

The basic idea is to add setter/getter methods to your model to accept/return an array of strings, and manage the relationship accordingly. So assuming you're field name is `tagbox` and your relationship is called `tags`, it could look something like this...

``` php
public function getTagboxAttribute()
{
    return $this->tags->lists('tag');
}

public function setTagboxAttribute($tags)
{
    $sync = [];
    foreach ($tags as $tag) {
        $newTag = Tag::firstOrCreate(['tag' => $tag]);
        $sync[] = $newTag->id;
    }

    $this->tags()->sync($sync);
}
```

**Comment by ariews** [comment]
Hi, thanks, for the explanation, its help

**Comment by scottbedard** [comment]
Anytime!
